apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-service-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      bb: db-service
  template:
    metadata:
      labels:
        bb: db-service
    spec:
      containers:
      - name: db-service
        image: ahmad2sabateen/db-server:latest
        imagePullPolicy: Always
      nodeSelector:
        db-node: "1"

---
apiVersion: v1
kind: Service
metadata:
  name: db-service-entrypoint
  namespace: default
spec:
  selector:
    bb: db-service
  ports:
  - port: 80
    targetPort: 80